version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerce_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      PG_DATABASE_URL: postgresql://postgres:admin@postgres:5432/ecommerce_db
      SECRET_KEY: oOUbyJRkOFhFqH7VVUWMqH-uYQuCyI3pRvHZYZRXfhgRY85a3gzflTFZNBDSOykN5Yw
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: sh -c "python run_seeds.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
